spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: '*'
            allowed-headers: '*'
      routes:
        - id: route-order
          uri: lb://service-order
          predicates:
            - Path=/order/**
        - id: route-product
          uri: lb://service-product
          predicates:
            - Path=/product/**

server:
  port: 80
