server.port=9010
spring.application.name=service-rabbitmq
spring.cloud.nacos.server-addr=127.0.0.1:8848

spring.rabbitmq.host=192.168.103.135
spring.rabbitmq.port=5672
spring.rabbitmq.username=test
spring.rabbitmq.password=123456

